name: build-iso
on: [pull_request]

jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v12
      - name: build iso 
        run: nix build --access-tokens github.com=${{ secrets.GH_TOKEN_FOR_UPDATES }} .#nixosConfigurations.egg.config.system.build.isoImage
